//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant_webProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int C_ID { get; set; }
        public string C_Name { get; set; }
        public string C_Phone { get; set; }
        public string C_Email { get; set; }
        public string C_Password { get; set; }
    }
}
